packages:
    - ./package
    - ./test
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    "@swc/core": true
    esbuild: false

catalogs:
    dep:
        "@swc/core": ^1.15.33
        get-tsconfig: ^4.14.0
        unplugin: ^3.0.0
    dev:
        rolldown: 1.0.0
        vite: 8.0.0
    peer:
        rolldown: ^1.0.0
        vite: ^8.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    # config
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    # tsdown
    - "@tsdown/*"
    - "tsdown"
